/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * eCos HDMI/DVE goldens from gxtest/goldens/dumps/.
 * Generated by gxtest/tools/goldens/gen_ecos_hdmi_goldens.py — do not edit by hand.
 */
#ifndef __GX6702_ECOS_GOLDENS_H
#define __GX6702_ECOS_GOLDENS_H

#include <linux/types.h>

#define GX6702_ECOS_DVE_WORDS	23
#define GX6702_ECOS_HDMI_FC_BYTES	0x20

struct gx6702_ecos_reg8 {
	u16 reg;
	u8 val;
};

struct gx6702_ecos_golden {
	u8 vic;
	u8 invidconf;
	u32 dve[GX6702_ECOS_DVE_WORDS];
	u8 hdmi_fc[GX6702_ECOS_HDMI_FC_BYTES]; /* regs 0x1000..0x101f */
	const struct gx6702_ecos_reg8 *hdmi_extra;
	u16 hdmi_extra_count;
};

extern const u16 gx6702_ecos_dve_offs[GX6702_ECOS_DVE_WORDS];
const struct gx6702_ecos_golden *gx6702_ecos_golden(unsigned int mode);

#endif
