# SPDX-License-Identifier: GPL-2.0+

obj-y += gx6702.o
obj-y += gx6702_usb.o
obj-y += gx6702_fuse.o
obj-$(CONFIG_VIDEO_GX6702) += gx6702_video.o gx6702_hdmi.o gx6702_ecos_goldens.o
obj-$(CONFIG_VIDEO_GX6702) += cmd_gxvideo.o
